### ISSUE TITLE
improve test coverage

### ISSUE THREAD

**Issue by mrmos** [kesne/with-react-hooks#3]
My IT director recently declared a company-wide push to get **all test coverage** to 100%. As part of this, he's also doing an audit to ensure that any dependencies we use also have 100% coverage. I'd really like to start using this repo, but unfortunately will not be able to until test coverage is improved. 

I really appreciate the work you're doing as far as pushing the envelope for enterprise applications. 

Cheers 🍺

**Comment by kesne** [comment]
@mrmos You're absolutely right, and in retrospect this was an oversight from #1. I remembered that I had [another project](https://github.com/airbnb/bossbat) I wrote previously with 100% test coverage and used that badge. Hopefully this new coverage satisfies your employer.

Fixed in https://github.com/kesne/with-react-hooks/commit/2068630ca851a3c4fde87d66b2a9efcf9be14d83.
